background {
    monitor =
    color = $color
    path = /usr/local/share/backgrounds/VolvoCars.jpg
    blur_passes = 0
    blur_size = 1
}

animations {
    enabled = false
}

label {
    monitor =
    text = Hi there, $USER! 👋
    font_size = 25
    font_family = CaskaydiaMono Nerd Font

    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 600, 100
    position = 0, 0
    halign = center
    valign = center

    outer_color = rgba(248, 249, 250, 0.92)      # Subtle light gray (Google-like)
    inner_color = rgba(66, 133, 244, 0.85)       # Google Blue, slightly transparent
    outline_thickness = 2

    font_family = CaskaydiaMono Nerd Font
    font_color = rgba(32, 33, 36, 1.0)           # Google Material dark gray

    placeholder_text =   Enter Password 󰈷 
    check_color = rgba(52, 168, 83, 1.0)         # Google green for success
    fail_text = <i>$PAMFAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}
