#!/usr/bin/env bash
# System menu. Typically assigned to a key bind (ie. Mod + /).

set -o errexit
set -o pipefail
set -o nounset

chosen=$(echo -e "  Lock\n󰽥  Suspend\n󰍃  Logout\n󰜉  Reboot\n󰐥  Shutdown" |
  fuzzel --dmenu "System...")

case "${chosen}" in
*Lock)
  swaylock  --indicator --indicator-radius 150 --indicator-thickness 10
  ;;
*Suspend)
  systemctl suspend
  ;;
*Logout)
  niri msg action quit
  ;;
*Reboot)
  systemctl reboot
  ;;
*Shutdown)
  systemctl poweroff
  ;;
esac
